version: '3.12'
services:
  bot:
    build:
      context: .
      network: host
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data/db:/db
    command: sqlite3 /373904.db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
        type: none
        device: /db
        o: bind
