version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data/db:/db
    command: sqlite3 /db/373904.db