version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    volumes:
      - ./373904.db:/app/373904.db
      - .:/app
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
    networks:
      - botnet

networks:
  botnet:
    driver: bridge